### PR TITLE
Add Docker command example to readme

### PR DESCRIPTION
**Pull request by rogierslag**
This adds an example command on how to "headlessly" request new certificates and get them as a file to the readme.

I also noticed the current container on Docker Hub is a bit outdated, perhaps it is an idea to add an _Automatic Build_ for it? https://docs.docker.com/docker-hub/builds/

### CODE REVIEW

**Comment by hsmade** [comment]
It thought I had auto build enabled, I'll go check. Thx for the PR

**Comment by hsmade** [comment]
Can you please fix the build? It's expecting readme.rst in the python install, so that needs to be adjusted as well

**Comment by rogierslag** [comment]
Done! Took some fiddling to determine how it would render exactly on Github, but it seems it works like this

**Comment by rogierslag** [comment]
Thanks for accepting, and thanks for the work you've put into this :)

**Pull request merged**
